# verified 2026-04-26 (live SSH from 192.168.0.100)
#goal definition
nav_msgs/Path path
string controller_id
string goal_checker_id
---
#result definition
uint8 SUCCESS=0
uint8 PLAN_FAILED=1
uint8 MOVE_FAILED=2
uint8 PATH_COLLISION=3
uint8 UNKNOWN=9
uint8 status
std_msgs/Empty result
---
#feedback
float32 distance_to_goal
float32 speed
