# verified 2026-04-26 (live SSH from 192.168.0.100)
uint8 LEVEL0=0
uint8 LEVEL1=1
uint8 LEVEL2=2
uint8 LEVEL3=3
uint8 LEVEL4=5
uint8 LEVEL5=5
uint8 LEVEL6=6
uint8 LEVEL7=7
uint8 LEVEL8=8
uint8 LEVEL9=9
uint8 LEVEL10=10
uint8 LEVEL11=11  # some macro for  level 0-11 

uint8 value # e.g. for level or value for some service setting
---
bool success   # indicate successful run of set uint8 service
string message # informational, e.g. for error messages
